export const urls = {
  addMovie: 'addMovie',
  getAllMovies: 'getAllBoxOfficeMovies',
  deleteMovie: 'deleteMovie',
  editMovie: 'updateMovie',
  getAllUsers: 'getAllUsers',
  deleteProfileByAdmin: 'deleteProfileByAdmin',
  deleteCoverByAdmin: 'deleteCoverByAdmin',
  accountSetting: 'isActiveByAdmin',
  sendMessageToUser: 'sendMessageToUser',
  getAllUserMessage: 'userMessages',
  getUserProfileById: 'getUserProfileById',
  getWeeklyScore: 'getWeeklyUserScore',
  getSeasonalScore: 'getSeasonalUserScore',
  getYearlyScore: 'getYearlyUserScore',
  updateFormat: 'updateFormat',
  login: 'signin',
  addInspiration: 'addInspiration',
  getAllInspirations: 'getAllInspirations',
  deleteInspiration: 'deleteInspiration',
  updateInspiration: 'updateInspiration',
  addUpdateBoostAudio: 'addUpdateBoostAudio',
  getAllBoostForAdmin: 'getAllBoostForAdmin',
  updaterevenue: 'setGrossRevenue',
}
