export const urls = {
  addMovie: 'addMovie',
  getAllMovies: 'getAllBoxOfficeMovies',
  deleteMovie: 'deleteMovie',
  editMovie: 'updateMovie',
  getAllUsers: 'getAllUsers',
  getAllGoalsImages: 'getAllGoalsImages',
  deleteGoalImage: 'DeleteGoalImage',
  addGoalImage: 'AddGoalImage',
  getAllTitlesAndInspiration: 'getInspirationsTypes',
  deleteTitle: 'deleteTitle',
  updateTitle: 'updateTitle',
  addTitle: 'addTitle',
  addFormat: 'addFormat',
  deleteFormat: 'deleteFormat',
  updateFormat: 'updateFormat',
  login: 'signin',
  addInspiration: 'addInspiration',
  getAllInspirations: 'getAllInspirations',
  deleteInspiration: 'deleteInspiration',
  updateInspiration: 'updateInspiration',
  addUpdateBoostAudio: 'addUpdateBoostAudio',
  getAllBoostForAdmin: 'getAllBoostForAdmin',
}
